version: "3.8"
services:
  nginx:
    build:
      context: .
      target: finalNginx
      args:
        API_URL: /
    networks:
      - reverse-proxy
      - back
    expose:
      - 80
    restart: always
    depends_on:
      node:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=test@test.ru

  node:
    build:
      context: .
      target: finalNode
    networks:
      - back
    expose:
      - 3001
    restart: always
    environment:
      - APP_PORT=3001
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3001 || exit 1
      timeout: 3s
      interval: 3s
      retries: 10
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
